apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: stacker-deployment
spec:
  selector:
    matchLabels:
      app: stacker
  replicas: 3 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: stacker
    spec:
      containers:
      - name: stacker
        image: stacker:latest
        imagePullPolicy: Never
        ports:
          - containerPort: 4000
