apiVersion: apps/v1
kind: Deployment
metadata:
  name: stacker-deployment
spec:
  selector:
    matchLabels:
      app: stacker
  replicas: 3 
  template:
    metadata:
      labels:
        app: stacker
        cluster: stacker
    spec:
      containers:
      - name: stacker
        image: stacker:latest
        imagePullPolicy: Never
        ports:
          - containerPort: 4000
          - containerPort: 4444
        env:
          - name: DATABASE_URL
            value: ecto://postgres:postgres@postgres/postgres
          - name: SECRET_KEY_BASE
            value: ZoIYBMEfwUxleUB+lC18tH7PYXkwo7NqJMvfDx7Bav4xyi0vS0VXnxcU6JgSHsq3
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
        readinessProbe:
          httpGet:
            path: /kubernetes/ready
            port: 4444
