apiVersion: v1
kind: Service
metadata:
  name: stacker
  labels:
    cluster: stacker
spec:
  selector:
    cluster: stacker
  clusterIP: None
  ports:
    - protocol: TCP
      port: 4444
      targetPort: 4444